[package]
name = "try-runtime-cli"
version = "0.10.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Cli command runtime testing and dry-running"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
remote-externalities = { version = "0.10.0-dev", path = "../../remote-externalities", package = "frame-remote-externalities" }
sc-cli = { version = "0.10.0-dev", path = "../../../../client/cli" }
sc-executor = { version = "0.10.0-dev", path = "../../../../client/executor" }
sc-service = { version = "0.10.0-dev", default-features = false, path = "../../../../client/service" }
sp-consensus-aura = { path = "../../../../primitives/consensus/aura" }
sp-consensus-babe = { path = "../../../../primitives/consensus/babe" }
sp-core = { version = "7", path = "../../../../primitives/core" }
sp-externalities = { version = "0.13", path = "../../../../primitives/externalities" }
sp-inherents = { path = "../../../../primitives/inherents" }
sp-io = { version = "7", path = "../../../../primitives/io" }
sp-keystore = { version = "0.13", path = "../../../../primitives/keystore" }
sp-runtime = { version = "7", path = "../../../../primitives/runtime" }
sp-rpc = { version = "6", path = "../../../../primitives/rpc" }
sp-state-machine = { version = "0.13", path = "../../../../primitives/state-machine" }
sp-timestamp = { path = "../../../../primitives/timestamp" }
sp-transaction-storage-proof = { path = "../../../../primitives/transaction-storage-proof" }
sp-version = { version = "5", path = "../../../../primitives/version" }
sp-debug-derive = { path = "../../../../primitives/debug-derive" }
sp-api = { path = "../../../../primitives/api" }
sp-weights = { version = "4", path = "../../../../primitives/weights" }
frame-try-runtime = { optional = true, path = "../../../../frame/try-runtime" }
substrate-rpc-client = { path = "../../rpc/client" }

async-trait = "0.1"
clap = { version = "4", features = ["derive"] }
hex = { version = "0.4", default-features = false }
log = "0.4"
parity-scale-codec = "3.4.0"
serde = "1"
serde_json = "1"
zstd = { version = "0.12", default-features = false }

[dev-dependencies]
assert_cmd = "2"
regex = "1"
substrate-cli-test-utils = { path = "../../../../test-utils/cli" }
tokio = "1"

[features]
try-runtime = ["sp-debug-derive/force-debug", "frame-try-runtime/try-runtime"]
